### ISSUE TITLE
support GitHub style alerts

### ISSUE THREAD

**Issue by Wxh16144** [rehypejs/rehype-github#3]
### Initial checklist

- [X] I read the [support docs](https://github.com/rehypejs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/rehypejs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/rehypejs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Arehypejs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

Have you considered supporting github-style alerts?  https://github.com/orgs/community/discussions/16925)

### Solution

like https://github.com/antfu/markdown-it-github-alerts

### Alternatives

unknow

**Comment by wooorm** [comment]
There should already be plugins like that.

And yes, when I have the time again to push and release this project, that too will be a part of it!

**Comment by ChristianMurphy** [comment]
In the meantime while this feature is being planned, developed, and tested.
There is a community plugin https://github.com/chrisweb/rehype-github-alerts which you could give a try.

**Comment by wooorm** [comment]
Solved as https://github.com/rehypejs/rehype-github/tree/main/packages/alert as well too. Will release in a minute! For more customization, the existing things are good!

**Comment by SupertigerDev** [comment]
This doesnt seem to work

EDIT: seems like when i remove all the ` it works, seems like a bug
```
> [!NOTE]
> • `limit` is limited to 100.   
> • Messages are ordered by date ascending.  
> • You can only specify `before` or `after` at once.  
> • If neither `before` or `after` are specified, last 50 (or `limit`) messages are are returned. 
```
> [!NOTE]
> • `limit` is limited to 100.   
> • Messages are ordered by date ascending.  
> • You can only specify `before` or `after` at once.  
> • If neither `before` or `after` are specified, last 50 (or `limit`) messages are are returned.

**Comment by JounQin** [comment]
@SupertigerDev Please open a new issue with a minimal but runnable reproduction.
